title: JP's cooking book
email: info@jamespan.org
description: a personal diary inspired by daydream and night anxiety
baseurl: "/"
url: "https://jamespan.org" 
theme: minima
plugins:
  - jekyll-feed
